#!/bin/bash
gcc -m32 -L/usr/lib32 -fno-pie -no-pie -c screen.c -o screen.o
nasm -f elf32 -o kernel.o kernel.asm
ld -m elf_i386 -Ttext 1000 kernel.o screen.o -o kernel
cat bootsect kernel /dev/zero | dd of=floppyA bs=512 count=2880
qemu-system-i386 -boot a -fda floppyA
